services:
  git:
    repositoriesRoot: "/repositories"
server:
  context-path: "/repositories"
  port: 8080
spring:
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
